services:
  strasboard:
    container_name: web-strasboard
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
      PORT: ${STRASBOARD_PORT:-80}
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "8080:${STRASBOARD_PORT:-80}"
